// Placeholder question bank — 30 questions across 6 topics.
// Diagnostics are plausible but illustrative; the founder should replace
// with curriculum-reviewed content before pilot launch.
//
// Shape matches the DB schema in supabase/migrations/0001_init.sql.

export type SeedQuestion = {
  id: string;
  topic:
    | "number_sense"
    | "operations"
    | "fractions_decimals"
    | "ratio_percent"
    | "geometry_measurement"
    | "word_problems_data";
  sub_topic: string;
  grade_level: "5" | "6" | "both";
  difficulty: "easy" | "medium" | "hard";
  cognitive_skill: "recall" | "application" | "reasoning";
  question_text: string;
  options: [string, string, string, string];
  correct_answer: "A" | "B" | "C" | "D";
  wrong_answer_diagnostics: Record<"A" | "B" | "C" | "D", string>;
  requires_explanation?: boolean;
  expected_time_seconds?: number;
};

export const QUESTIONS: SeedQuestion[] = [
  // ============ Number Sense & Place Value ============
  {
    id: "ns-001",
    topic: "number_sense",
    sub_topic: "place value",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "What is the place value of 7 in the number 4,7 5 2?",
    options: ["7", "70", "700", "7,000"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Reads the digit value, ignoring place — confuses digit with place value.",
      B: "Off-by-one in place value (tens instead of hundreds).",
      C: "Correct.",
      D: "Off-by-one in place value (thousands instead of hundreds).",
    },
    expected_time_seconds: 45,
  },
  {
    id: "ns-002",
    topic: "number_sense",
    sub_topic: "reading large numbers",
    grade_level: "both",
    difficulty: "medium",
    cognitive_skill: "recall",
    question_text: "Which number is 'three lakh four thousand and fifty'?",
    options: ["304,050", "340,050", "300,450", "3,04,050"],
    correct_answer: "A",
    wrong_answer_diagnostics: {
      A: "Correct.",
      B: "Misreads lakh-thousand boundary.",
      C: "Misplaces tens place.",
      D: "Same value, Indian notation — may be a formatting confusion, not a concept gap.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "ns-003",
    topic: "number_sense",
    sub_topic: "number line / negatives",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text: "Which number is greater: -7 or -3?",
    options: ["-7", "-3", "They are equal", "Cannot be compared"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Treats magnitude of a negative as 'bigger' — common misconception that -7 > -3.",
      B: "Correct.",
      C: "Guess or unfamiliarity with negatives.",
      D: "Guess or unfamiliarity with negatives.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "ns-004",
    topic: "number_sense",
    sub_topic: "rounding",
    grade_level: "both",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text: "Round 4,758 to the nearest hundred.",
    options: ["4,700", "4,750", "4,800", "5,000"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Rounds down — ignores the tens digit.",
      B: "Rounds to nearest fifty — misunderstands 'nearest hundred.'",
      C: "Correct.",
      D: "Rounds to nearest thousand — misreads the instruction.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "ns-005",
    topic: "number_sense",
    sub_topic: "ordering",
    grade_level: "both",
    difficulty: "hard",
    cognitive_skill: "reasoning",
    question_text:
      "Arrange from smallest to largest: 10,203 | 10,023 | 1,203 | 10,230",
    options: [
      "1,203 < 10,023 < 10,203 < 10,230",
      "1,203 < 10,203 < 10,023 < 10,230",
      "10,023 < 10,203 < 10,230 < 1,203",
      "1,203 < 10,230 < 10,203 < 10,023",
    ],
    correct_answer: "A",
    wrong_answer_diagnostics: {
      A: "Correct.",
      B: "Confuses 10,023 vs 10,203 — weak on reading internal zeros.",
      C: "Treats number of digits incorrectly — thinks 1,203 is largest.",
      D: "General confusion in comparing within the same digit length.",
    },
    expected_time_seconds: 90,
  },

  // ============ Operations & Arithmetic ============
  {
    id: "op-001",
    topic: "operations",
    sub_topic: "multi-digit multiplication",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "23 × 4 = ?",
    options: ["82", "92", "94", "102"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Forgets to carry from units.",
      B: "Correct.",
      C: "Off-by-two — calculation slip.",
      D: "Multiplies 24 × 4 instead — misread the number.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "op-002",
    topic: "operations",
    sub_topic: "long division",
    grade_level: "both",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text: "378 ÷ 6 = ?",
    options: ["62", "63", "64", "73"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Error in last step — subtraction mistake.",
      B: "Correct.",
      C: "Off-by-one on quotient.",
      D: "Swaps a digit — likely place-value error during long division.",
    },
    requires_explanation: true,
    expected_time_seconds: 120,
  },
  {
    id: "op-003",
    topic: "operations",
    sub_topic: "order of operations",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "reasoning",
    question_text: "What is 3 + 4 × 5?",
    options: ["35", "23", "27", "19"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Left-to-right: 3+4=7, 7×5=35 — BODMAS not applied.",
      B: "Correct.",
      C: "Adds then multiplies partially.",
      D: "Random error.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "op-004",
    topic: "operations",
    sub_topic: "multi-digit multiplication",
    grade_level: "both",
    difficulty: "hard",
    cognitive_skill: "application",
    question_text: "125 × 24 = ?",
    options: ["2,500", "3,000", "3,250", "3,500"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Forgets to add second partial product — classic multi-digit slip.",
      B: "Correct.",
      C: "Carry error in addition of partial products.",
      D: "Multiplies 125 × 28 instead.",
    },
    expected_time_seconds: 120,
  },
  {
    id: "op-005",
    topic: "operations",
    sub_topic: "mental arithmetic",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "What is 1000 − 475?",
    options: ["425", "525", "535", "625"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Borrow error — subtracts 575 mentally.",
      B: "Correct.",
      C: "Off-by-ten slip.",
      D: "Major subtraction error.",
    },
    expected_time_seconds: 60,
  },

  // ============ Fractions & Decimals ============
  {
    id: "fd-001",
    topic: "fractions_decimals",
    sub_topic: "concept of fractions",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "Which fraction is larger: 1/2 or 1/4?",
    options: ["1/2", "1/4", "They are equal", "Depends on the whole"],
    correct_answer: "A",
    wrong_answer_diagnostics: {
      A: "Correct.",
      B: "Treats the denominator as the whole value — 'bigger number = bigger fraction' misconception.",
      C: "Guess.",
      D: "Over-thinks, but reveals uncertainty about the core concept.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "fd-002",
    topic: "fractions_decimals",
    sub_topic: "equivalent fractions",
    grade_level: "both",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text: "Which fraction is equivalent to 3/4?",
    options: ["6/7", "9/12", "4/5", "7/8"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Adds 3 to both numerator and denominator — confuses adding with multiplying.",
      B: "Correct.",
      C: "Picks a fraction numerically close but not equivalent.",
      D: "Picks a fraction numerically close but not equivalent.",
    },
    requires_explanation: true,
    expected_time_seconds: 75,
  },
  {
    id: "fd-003",
    topic: "fractions_decimals",
    sub_topic: "adding fractions",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text: "1/4 + 2/4 = ?",
    options: ["3/8", "3/4", "2/16", "1/2"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Adds numerators AND denominators — core fraction addition misconception.",
      B: "Correct.",
      C: "Multiplies everything — confusion between operations on fractions.",
      D: "Simplifies incorrectly or guesses.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "fd-004",
    topic: "fractions_decimals",
    sub_topic: "adding fractions (unlike)",
    grade_level: "6",
    difficulty: "hard",
    cognitive_skill: "reasoning",
    question_text: "1/2 + 1/3 = ?",
    options: ["2/5", "1/6", "5/6", "2/6"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Adds numerators and denominators — same fractions-are-two-separate-numbers misconception.",
      B: "Multiplies the denominators only.",
      C: "Correct.",
      D: "Finds common denominator but forgets to convert numerators.",
    },
    requires_explanation: true,
    expected_time_seconds: 120,
  },
  {
    id: "fd-005",
    topic: "fractions_decimals",
    sub_topic: "decimal place value",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "Which is greater: 0.5 or 0.45?",
    options: ["0.5", "0.45", "They are equal", "Cannot tell"],
    correct_answer: "A",
    wrong_answer_diagnostics: {
      A: "Correct.",
      B: "Treats more digits as 'bigger' — classic 'longer number wins' misconception with decimals.",
      C: "Concept-level confusion.",
      D: "Concept-level confusion.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "fd-006",
    topic: "fractions_decimals",
    sub_topic: "fraction-decimal conversion",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text: "What is 3/4 as a decimal?",
    options: ["0.34", "0.43", "0.75", "0.8"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Reads the digits: 3 and 4 — no conversion understanding.",
      B: "Same as A, reversed.",
      C: "Correct.",
      D: "Approximates — likely guessing.",
    },
    expected_time_seconds: 60,
  },

  // ============ Ratio, Proportion & Percentages ============
  {
    id: "rp-001",
    topic: "ratio_percent",
    sub_topic: "percent of whole",
    grade_level: "6",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "What is 10% of 200?",
    options: ["10", "20", "50", "100"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Reads only the % number.",
      B: "Correct.",
      C: "Divides by 4 — confuses 25% with 10%.",
      D: "Divides by 2 — confuses 50% with 10%.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "rp-002",
    topic: "ratio_percent",
    sub_topic: "unit conversions",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "How many centimetres are in 2.5 metres?",
    options: ["25", "250", "2,500", "0.025"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Multiplies by 10 instead of 100.",
      B: "Correct.",
      C: "Multiplies by 1000 — confuses m→cm with m→mm.",
      D: "Divides instead of multiplying.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "rp-003",
    topic: "ratio_percent",
    sub_topic: "ratio basics",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text:
      "A box has 3 red balls and 5 blue balls. What is the ratio of red to blue?",
    options: ["3:5", "5:3", "3:8", "5:8"],
    correct_answer: "A",
    wrong_answer_diagnostics: {
      A: "Correct.",
      B: "Reverses the ratio.",
      C: "Compares red to total instead of red to blue.",
      D: "Compares blue to total.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "rp-004",
    topic: "ratio_percent",
    sub_topic: "percent word problem",
    grade_level: "6",
    difficulty: "hard",
    cognitive_skill: "reasoning",
    question_text:
      "A shirt costs ₹800. The shopkeeper offers 25% off. What is the final price?",
    options: ["₹200", "₹575", "₹600", "₹775"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Gives the discount amount, not the final price — misreads the question.",
      B: "Calculation slip in discount.",
      C: "Correct.",
      D: "Subtracts ₹25 — treats the percent as rupees.",
    },
    requires_explanation: true,
    expected_time_seconds: 120,
  },

  // ============ Geometry & Measurement ============
  {
    id: "gm-001",
    topic: "geometry_measurement",
    sub_topic: "perimeter",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text:
      "What is the perimeter of a square with side length 6 cm?",
    options: ["12 cm", "18 cm", "24 cm", "36 cm"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Adds only two sides.",
      B: "Adds three sides.",
      C: "Correct.",
      D: "Calculates area (6×6) instead of perimeter.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "gm-002",
    topic: "geometry_measurement",
    sub_topic: "area",
    grade_level: "both",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text:
      "What is the area of a rectangle with length 8 cm and width 5 cm?",
    options: ["13 cm²", "26 cm²", "40 cm²", "80 cm²"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Adds length and width — confuses perimeter formula with area.",
      B: "Calculates perimeter.",
      C: "Correct.",
      D: "Multiplies an extra factor of 2 — confused formula.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "gm-003",
    topic: "geometry_measurement",
    sub_topic: "angles",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text:
      "Two angles of a triangle are 40° and 70°. What is the third angle?",
    options: ["60°", "70°", "80°", "110°"],
    correct_answer: "A",
    wrong_answer_diagnostics: {
      A: "Correct.",
      B: "Picks one of the given angles — didn't apply sum=180°.",
      C: "Off by 20°.",
      D: "Uses 180° − 70° only, ignoring the 40°.",
    },
    expected_time_seconds: 75,
  },
  {
    id: "gm-004",
    topic: "geometry_measurement",
    sub_topic: "volume",
    grade_level: "6",
    difficulty: "hard",
    cognitive_skill: "reasoning",
    question_text:
      "What is the volume of a cube with side length 4 cm?",
    options: ["12 cm³", "16 cm³", "48 cm³", "64 cm³"],
    correct_answer: "D",
    wrong_answer_diagnostics: {
      A: "Adds the sides (4+4+4) — confuses volume with perimeter-like sum.",
      B: "Squares instead of cubing — confuses volume with area.",
      C: "Partial: multiplies by 3 sides.",
      D: "Correct.",
    },
    expected_time_seconds: 90,
  },
  {
    id: "gm-005",
    topic: "geometry_measurement",
    sub_topic: "basic shapes",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "recall",
    question_text: "How many sides does a hexagon have?",
    options: ["5", "6", "7", "8"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Confuses with pentagon.",
      B: "Correct.",
      C: "Off-by-one.",
      D: "Confuses with octagon.",
    },
    expected_time_seconds: 30,
  },

  // ============ Word Problems & Data Interpretation ============
  {
    id: "wp-001",
    topic: "word_problems_data",
    sub_topic: "single-step",
    grade_level: "both",
    difficulty: "easy",
    cognitive_skill: "application",
    question_text:
      "A pencil costs ₹5. How much will 12 pencils cost?",
    options: ["₹17", "₹50", "₹60", "₹72"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Adds instead of multiplying — key operation misidentified.",
      B: "Uses 10 instead of 12 — misreads.",
      C: "Correct.",
      D: "Multiplies by 6 — calculation slip.",
    },
    expected_time_seconds: 60,
  },
  {
    id: "wp-002",
    topic: "word_problems_data",
    sub_topic: "multi-step",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "reasoning",
    question_text:
      "Riya had ₹200. She bought 3 notebooks at ₹40 each. How much money is left?",
    options: ["₹40", "₹80", "₹120", "₹160"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Multiplies only 40 × something else — wrong step order.",
      B: "Correct.",
      C: "Subtracts only one notebook's cost.",
      D: "Subtracts ₹40 once, ignores '3'.",
    },
    requires_explanation: true,
    expected_time_seconds: 90,
  },
  {
    id: "wp-003",
    topic: "word_problems_data",
    sub_topic: "bar graph reading",
    grade_level: "both",
    difficulty: "medium",
    cognitive_skill: "application",
    question_text:
      "A bar graph shows rainfall: Jan 20mm, Feb 30mm, Mar 50mm, Apr 40mm. Which month had the MOST rain?",
    options: ["January", "February", "March", "April"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Misreads the graph.",
      B: "Picks a mid-range value.",
      C: "Correct.",
      D: "Picks the last bar without comparing.",
    },
    expected_time_seconds: 45,
  },
  {
    id: "wp-004",
    topic: "word_problems_data",
    sub_topic: "table interpretation",
    grade_level: "6",
    difficulty: "medium",
    cognitive_skill: "reasoning",
    question_text:
      "A table shows students in 4 classes: 5A=28, 5B=32, 5C=30, 5D=25. What is the total?",
    options: ["105", "110", "115", "120"],
    correct_answer: "C",
    wrong_answer_diagnostics: {
      A: "Subtraction error during addition.",
      B: "Misses adding one class.",
      C: "Correct.",
      D: "Over-counts or rounds up.",
    },
    expected_time_seconds: 75,
  },
  {
    id: "wp-005",
    topic: "word_problems_data",
    sub_topic: "multi-step hard",
    grade_level: "6",
    difficulty: "hard",
    cognitive_skill: "reasoning",
    question_text:
      "A water tank holds 500 litres. Each day 40 litres are used. After how many full days will there be less than 100 litres left?",
    options: ["9 days", "10 days", "11 days", "12 days"],
    correct_answer: "B",
    wrong_answer_diagnostics: {
      A: "Off-by-one error — miscounts the boundary.",
      B: "Correct.",
      C: "Misinterprets 'less than 100' as '≤ 100'.",
      D: "Miscalculates the daily consumption.",
    },
    requires_explanation: true,
    expected_time_seconds: 150,
  },
];

// Sanity check: count per topic should roughly match PRD §5.1 targets.
